services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: always

  mariadb:
    build: requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    build: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "80:80"
    restart: always
    volumes:
      - wd-data:/var/www/html
      - wd-files:/var/www/html/wp-content/uploads


volumes:
  wd-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wd-data
      o: bind
  wd-files:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wd-files
      o: bind

networks:
  all:
    driver: bridge