name: inception

services:

  nginx:
    build: requirements/nginx
    env_file:       .env
    ports:
      - "443:443"
    volumes:
      - wd-files:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    build: requirements/mariadb
    env_file:       .env
    networks:
      - inception_network
    volumes:
      - db-data:/var/lib/mysql
    restart: on-failure

  wordpress:
    build: requirements/wordpress
    env_file:      .env
    networks:
      - inception_network
    volumes:
      - wd-files:/var/www/html
    depends_on:
      - mariadb
      - redis
    restart: on-failure

  adminer:
    # image: adminer
    build: requirements/adminer
    ports:
      - 8080:8080
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: on-failure

  redis:
    build: requirements/redis
    networks:
      - inception_network
    restart: on-failure

  ftp:
    build: requirements/ftp
    env_file: .env
    environment:
      - IP_ADDR=${IP_ADDR}
    ports:
      - "21:21"
      - 30000-30009:30000-30009
    networks:
      - inception_network
    volumes:
      - wd-files:/var/www/html
    restart: on-failure

  portainer:
    build: ./requirements/portainer/
    env_file: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - prt-files:/data
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception_network
    ports:
      - "9443:9443"

#   gatsby:
#     build: ./requirements/gatsby
#     volumes:
#       - gatsby-data:/usr/src/app/public
#       - ~/my-portfolio:/usr/src/app
#     ports:
#       - "8001:8001"
#     environment:
#       NODE_ENV: development
#       CHOKIDAR_USEPOLLING: "1"
#       GATSBY_WEBPACK_PUBLICPATH: "/"
#     command: gatsby develop -H 0.0.0.0
#     networks:
#       - inception_network
#     restart: on-failure

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/db-data
      o: bind
  wd-files:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wd-files
      o: bind

  # bonus
  prt-files:
    name: prt
    driver: local
    driver_opts:
      type: none
      device: ~/data/portainer
      o: bind
#   gatsby-data:
#     driver: local
#     driver_opts:
#       type: none
#       device: ~/data/gatsby-data
#       o: bind

networks:
  inception_network:
    driver: bridge