services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: always

  mariadb:
    build: requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    restart: always

volumes:
  wd-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wd-data
      o: bind
  wd-files:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wd-files
      o: bind

networks:
  all:
    driver: bridge