# FROM node:14

# WORKDIR /usr/src/app

# COPY ~/my-portfolio/package*.json ./

# RUN npm install

# COPY ~/my-portfolio .

# EXPOSE 8001

# ENV NODE_ENV=development
# ENV CHOKIDAR_USEPOLLING=1
# ENV GATSBY_WEBPACK_PUBLICPATH=/

# CMD ["npm", "run", "develop"]